title: "Cryptography for Everyone"
description: "Cryptography and CTF-related things made as simple as possible!"
theme: jekyll-theme-hacker

url: "https://vodomerka-rgb.github.io"
baseurl: "/cryptography-for-everyone"

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/

show_excerpts: true
